// todo: License

#ifndef ARDEP_INCLUDE_DT_BINDINGS_HV_SHIELD_V2_H_
#define ARDEP_INCLUDE_DT_BINDINGS_HV_SHIELD_V2_H_

#define HV_SHIELD_V2_OUTPUTS 0
#define HV_SHIELD_V2_INPUTS 1
#define HV_SHIELD_V2_FAULT_PINS 2

#endif
