// todo: License

#ifndef ARDEP_INCLUDE_DT_BINDINGS_HV_SHIELD_V2_H_
#define ARDEP_INCLUDE_DT_BINDINGS_HV_SHIELD_V2_H_

#define HV_SHIELD_V2_OUTPUTS 0
#define HV_SHIELD_V2_INPUTS 1
#define HV_SHIELD_V2_FAULT_PINS 2

// also see hv_shield_v2.c
#define HV_SHIELD_V2_INPUT_BASE 0x00
#define HV_SHIELD_V2_OUTPUT_BASE 0x08
#define HV_SHIELD_V2_FAULT_BASE 0x10

#define HV_SHIELD_V2_BASE_MASK 0xf8

#define HV_SHIELD_V2_INPUT(pin) (HV_SHIELD_V2_INPUT_BASE | pin)
#define HV_SHIELD_V2_OUTPUT(pin) (HV_SHIELD_V2_OUTPUT_BASE | pin)
#define HV_SHIELD_V2_FAULT(pin) (HV_SHIELD_V2_FAULT_BASE | pin)

#endif
