manifest:
  self:
    path: ardep
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: frickly-systems
      url-base: https://github.com/frickly-systems

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2.0
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - segger
          - hal_st
          - mcuboot
          - mbedtls
          - littlefs
    - name: zephboards
      url: https://github.com/dragonlock2/zephyrboards.git
      revision: 9443ad0ebe547a140ec54790687ae8b4d4e0cd34
    - name: iso14229
      remote: frickly-systems
      revision: zephyr
    - name: cannectivity
      url: https://github.com/CANnectivity/cannectivity.git
      revision: v1.2.1
      path: modules/lib/cannectivity
