manifest:
  self:
    path: ardep
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2.0
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - segger
          - hal_st
          - mcuboot
          - mbedtls
    - name: zephboards
      url: https://github.com/dragonlock2/zephyrboards.git
      revision: 9443ad0ebe547a140ec54790687ae8b4d4e0cd34
    - name: iso14229
      url: https://github.com/driftregion/iso14229.git
      revision: 4a9394163d817b6ec55c3ad5c8e937bd51efeadf
