/*
 * Copyright (C) Frickly Systems GmbH
 * Copyright (C) MBition GmbH
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ARDEP_ISO14229_NRC_H
#define ARDEP_ISO14229_NRC_H

/**
 * @brief Negative Response Codes (NRCs)
 *
 * Defined in ISO14229-1:2020 Annex A, Table A.1
 */
enum uds_error {
  UDS_POSITIVE_RESPONSE = 0,
  // UDS_OK = 0,
  // 0x01 to 0x0F ISOSAEReserved
  UDS_NRC_GENERAL_REJECT = 0x10,
  UDS_NRC_SERVICE_NOT_SUPPORTED = 0x11,
  UDS_NRC_SUB_FUNCTION_NOT_SUPPORTED = 0x12,
  UDS_NRC_INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT = 0x13,
  UDS_NRC_RESPONSE_TOO_LONG = 0x14,
  // 0x15 to 0x20 ISOSAEReserved
  UDS_NRC_BUSY_REPEAT_REQUEST = 0x21,
  UDS_NRC_CONDITIONS_NOT_CORRECT = 0x22,
  // 0x23 ISOSAEReserved
  UDS_NRC_REQUEST_SEQUENCE_ERROR = 0x24,
  UDS_NRC_NO_RESPONSE_FROM_SUBNET_COMPONENT = 0x25,
  UDS_NRC_FAILURE_PREVENTS_EXECUTION_OF_REQUESTED_ACTION = 0x26,
  // 0x27 to 0x30 ISOSAEReserved
  UDS_NRC_REQUEST_OUT_OF_RANGE = 0x31,
  // 0x32 is reserved by ISO14229-1:2020
  UDS_NRC_SECURITY_ACCESS_DENIED = 0x33,
  UDS_NRC_AUTHENTICATION_REQUIRED = 0x34,
  UDS_NRC_INVALID_KEY = 0x35,
  UDS_NRC_EXCEED_NUMBER_OF_ATTEMPTS = 0x36,
  UDS_NRC_REQUIRED_TIME_DELAY_NOT_EXPIRED = 0x37,
  UDS_NRC_SECURE_DATA_TRANSMISSION_REQUIRED = 0x38,
  UDS_NRC_SECURE_DATA_TRANSMISSION_NOT_ALLOWED = 0x39,
  UDS_NRC_SECURE_DATA_VERIFICATION_FAILED = 0x3A,
  // 0x3B to 0x4F ISOSAEReserved
  UDS_NRC_CERTIFICATE_VERIFICATION_FAILED_INVALID_TIME_PERIOD = 0x50,
  UDS_NRC_CERTIFICATE_VERIFICATION_FAILED_INVALID_SIGNATURE = 0x51,
  UDS_NRC_CERTIFICATE_VERIFICATION_FAILED_INVALID_CHAIN_OF_TRUST = 0x52,
  UDS_NRC_CERTIFICATE_VERIFICATION_FAILED_INVALID_TYPE = 0x53,
  UDS_NRC_CERTIFICATE_VERIFICATION_FAILED_INVALID_FORMAT = 0x54,
  UDS_NRC_CERTIFICATE_VERIFICATION_FAILED_INVALID_CONTENT = 0x55,
  UDS_NRC_CERTIFICATE_VERIFICATION_FAILED_INVALID_SCOPE = 0x56,
  UDS_NRC_CERTIFICATE_VERIFICATION_FAILED_INVALID_CERTIFICATE = 0x57,
  UDS_NRC_OWNERSHIP_VERIFICATION_FAILED = 0x58,
  UDS_NRC_CHALLENGE_CALCULATION_FAILED = 0x59,
  UDS_NRC_SETTING_ACCESS_RIGHTS_FAILED = 0x5A,
  UDS_NRC_SESSION_KEY_CREATION_OR_DERIVATION_FAILED = 0x5B,
  UDS_NRC_CONFIGURATION_DATA_USAGE_FAILED = 0x5C,
  UDS_NRC_DE_AUTHENTICATION_FAILED = 0x5D,
  // 0x5E to 0x6F ISOSAEReserved
  UDS_NRC_UPLOAD_DOWNLOAD_NOT_ACCEPTED = 0x70,
  UDS_NRC_TRANSFER_DATA_SUSPENDED = 0x71,
  UDS_NRC_GENERAL_PROGRAMMING_FAILURE = 0x72,
  UDS_NRC_WRONG_BLOCK_SEQUENCE_COUNTER = 0x73,
  // 0x74 to 0x77 ISOSAEReserved
  UDS_NRC_REQUEST_CORRECTLY_RECEIVED_RESPONSE_PENDING = 0x78,
  // 0x79 to 0x7D ISOSAEReserved
  UDS_NRC_SUB_FUNCTION_NOT_SUPPORTED_IN_ACTIVE_SESSION = 0x7E,
  UDS_NRC_SERVICE_NOT_SUPPORTED_IN_ACTIVE_SESSION = 0x7F,
  // 0x80 ISOSAEReserved
  UDS_NRC_RPM_TOO_HIGH = 0x81,
  UDS_NRC_RPM_TOO_LOW = 0x82,
  UDS_NRC_ENGINE_IS_RUNNING = 0x83,
  UDS_NRC_ENGINE_IS_NOT_RUNNING = 0x84,
  UDS_NRC_ENGINE_RUN_TIME_TOO_LOW = 0x85,
  UDS_NRC_TEMPERATURE_TOO_HIGH = 0x86,
  UDS_NRC_TEMPERATURE_TOO_LOW = 0x87,
  UDS_NRC_VEHICLE_SPEED_TOO_HIGH = 0x88,
  UDS_NRC_VEHICLE_SPEED_TOO_LOW = 0x89,
  UDS_NRC_THROTTLE_PEDAL_TOO_HIGH = 0x8A,
  UDS_NRC_THROTTLE_PEDAL_TOO_LOW = 0x8B,
  UDS_NRC_TRANSMISSION_RANGE_NOT_IN_NEUTRAL = 0x8C,
  UDS_NRC_TRANSMISSION_RANGE_NOT_IN_GEAR = 0x8D,
  // 0x8E ISOSAEReserved
  UDS_NRC_BRAKE_SWITCH_NOT_CLOSED = 0x8F,
  UDS_NRC_SHIFTER_LEVER_NOT_IN_PARK = 0x90,
  UDS_NRC_TORQUE_CONVERTER_CLUTCH_LOCKED = 0x91,
  UDS_NRC_VOLTAGE_TOO_HIGH = 0x92,
  UDS_NRC_VOLTAGE_TOO_LOW = 0x93,
  UDS_NRC_RESOURCE_TEMPORARILY_NOT_AVAILABLE = 0x94,

  UDS_NRC_RESERVED_FOR_SPECIFIC_CONDITIONS_NOT_CORRECT_START = 0x95,
  UDS_NRC_RESERVED_FOR_SPECIFIC_CONDITIONS_NOT_CORRECT_END = 0xEF,
  UDS_NRC_VEHICLE_MANUFACTURER_SPECIFIC_CONDITIONS_NOT_CORRECT_START = 0xF0,
  UDS_NRC_VEHICLE_MANUFACTURER_SPECIFIC_CONDITIONS_NOT_CORRECT_END = 0xFE,
  // 0xFF ISOSAEReserved
};

#endif  // ARDEP_ISO14229_NRC_H