name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.28.4
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: zephyr-workspace/ardep

      - name: Initialize
        working-directory: zephyr-workspace/ardep
        run: |
          west init -l --mf ./west.yml .
          west update -o=--depth=1 -n

      - name: Run tests
        working-directory: zephyr-workspace/ardep
        run: |
          west twister -T ardep/tests -p native_sim -v --inline-logs
